# master - then tag repo and tag docker with tag: need to figure this
# develop - run this
# branch - tag docker with commit perhaps

steps:
  - id: 'compile app'
    name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    waitFor: ['-']

  - id: 'unit tests'
    name: 'gcr.io/cloud-builders/npm'
    args: ['test']
    waitFor: ['compile app']

  - id: 'integration/pact/component tests'
    name: 'gcr.io/cloud-builders/curl'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        echo "hello"
    waitFor: ['unit tests']

  - id: 'sonar check'
    name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
    args:
      - '-Dsonar.host.url=http://35.224.185.47/'
      - '-Dsonar.login=$$SONAR_LOGIN'
      - '-Dsonar.projectKey=controller'
      - '-Dsonar.sources=.'
    secretEnv: ['SONAR_LOGIN']

  - id: 'push image'
    name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'gcr.io/$PROJECT_ID/rushController:${COMMIT_SHA}',
      '.'
    ]
    waitFor: ['integration/pact/component tests']

  # Generate a kubeconfig file for the given GKE cluster.
  - id: 'kubeconfig for build cluster'
    name: 'gcr.io/cloud-builders/gcloud'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
      - 'KUBECONFIG=/kube/config'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        CLUSTER=$$(gcloud config get-value container/cluster)
        PROJECT=$$(gcloud config get-value core/project)
        ZONE=$$(gcloud config get-value compute/zone)

        gcloud container clusters get-credentials "$${CLUSTER}" \
          --project "$${PROJECT}" \
          --zone "$${ZONE}"
    volumes:
      - name: 'kube'
        path: /kube

  - id: 'deploy to build cluster'
    name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/', '--namespace=test-$BUILD_ID']
    waitFor: ['kubeconfig for build cluster']
    volumes:
      - name: 'kube'
        path: /kube

  - id: 'deploy service'
    name: 'gcr.io/cloud-builders/kubectl'
    args: [
      'set',
      'image',
      'deployment',
      'rushController',
      'rushController=gcr.io/$PROJECT_ID/rushController:${COMMIT_SHA}'
    ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=[COMPUTE-ZONE]'
      - 'CLOUDSDK_CONTAINER_CLUSTER=[CLUSTER]'

  - id: 'e2e/system tests'
    name: 'gcr.io/cloud-builders/curl'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        echo "hello"
    waitFor: ['deploy service']

  - id: 'delete namespace'
    name: 'gcr.io/cloud-builders/kubectl'
    args: ['delete', 'namespaces', 'test-$BUILD_ID']
    waitFor: ['e2e/system tests']

  - id: 'push dev image'
    name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'gcr.io/$PROJECT_ID/rushController:dev',
      '.'
    ]
    waitFor: ['delete namespace']

secrets:
  - kmsKeyName: 'projects/${PROJECT_ID}/locations/global/keyRings/rush-build/cryptoKeys/rush-build'
    secretEnv:
      SONAR_LOGIN: CiQAyglR/0ayS4n8Njkjluj/TAEufrGnIG3VNcNLDhHmELDGuqUSUACI5pchHwQFfSQCHC4l8VMQB/OM8RzbZxKzsUMI5sjXTUtFBLEE1sRyX45K5+saUkeeXqLL93hRw1OnkR7wPDI4+X30UH7JW7zzhzPGnriC