FROM iofog/node-alpine-x86:8.16.0 AS builder

ARG PKG_VERSION

WORKDIR /tmp

RUN npm config set unsafe-perm true

RUN npm i -g npm

COPY package.json .

COPY package-lock.json .

COPY scripts .

RUN npm i

COPY . .

RUN npm version $PKG_VERSION --allow-same-version

RUN npm pack

FROM iofog/node-alpine-x86:8.16.0

RUN apk add -y sudo logrotate
ENV NODE_ENV=development

COPY logrotate.conf /etc/logrotate.conf

# https://stackoverflow.com/questions/52196518/could-not-get-uid-gid-when-building-node-docker
# Workaround until we fix our node alpine image
RUN npm config set unsafe-perm true

COPY --from=builder /tmp/iofogcontroller-*.tgz /tmp/iofog-controller.tgz

RUN npm i --unsafe-perm -g /tmp/iofog-controller.tgz && \
  rm -rf /tmp/iofog-controller.tgz && \
  iofog-controller config dev-mode --on

CMD [ "node", "/usr/local/lib/node_modules/iofogcontroller/src/server.js" ]
