FROM node:fermium AS builder

ARG PKG_VERSION

WORKDIR /tmp

# Required by node-gyp
RUN sudo apt install python3.8

RUN npm config set unsafe-perm true

RUN npm i -g npm

COPY package.json .

COPY . .

RUN npm i --build-from-source

RUN npm version $PKG_VERSION --allow-same-version --no-git-tag-version

RUN npm pack

FROM node:fermium-alpine3.12

RUN apk add sudo logrotate g++ make

ENV NODE_ENV=development

COPY logrotate.conf /etc/logrotate.conf

# Install python/pip
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools

# https://stackoverflow.com/questions/52196518/could-not-get-uid-gid-when-building-node-docker
# Workaround until we fix our node alpine image
RUN npm config set unsafe-perm true

COPY --from=builder /tmp/iofogcontroller-*.tgz /tmp/iofog-controller.tgz

RUN npm i --unsafe-perm -g /tmp/iofog-controller.tgz && \
  rm -rf /tmp/iofog-controller.tgz && \
  iofog-controller config dev-mode --on

CMD [ "node", "/usr/local/lib/node_modules/iofogcontroller/src/server.js" ]
