const fogState = {
  UNKNOWN: 'UNKNOWN',
  RUNNING: 'RUNNING',
  STOPPED: 'STOPPED',
  WAITING: 'WAITING',
  WARNING: 'WARNING',
  DEBUGGING: 'DEBUGGING',
  DEPROVISIONED: 'DEPROVISIONED',
  ERROR: 'ERROR',
  NOT_PROVISIONED: 'NOT_PROVISIONED'
}

module.exports = fogState
