const microserviceState = {
  QUEUED: 'QUEUED',
  PULLING: 'PULLING',
  STARTING: 'STARTING',
  RUNNING: 'RUNNING',
  STOPPING: 'STOPPING',
  DELETING: 'DELETING',
  MARKED_FOR_DELETION: 'MARKED_FOR_DELETION',
  UPDATING: 'UPDATING',
  RESTARTING: 'RESTARTING',
  STUCK_IN_RESTART: 'STUCK_IN_RESTART',
  UNKNOWN: 'UNKNOWN',
  FAILED: 'FAILED',
  DELETED: 'DELETED',
  EXITING: 'EXITING',
  STOPPED: 'STOPPED',
  CREATING: 'CREATING'
}

const microserviceExecState = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE'
}

module.exports = { microserviceState, microserviceExecState }
