port: $NATS_SERVER_PORT
server_name: "$SERVER_NAME"
pid_file: /home/runner/run/nats.pid
http_port: $NATS_HTTP_PORT

# Operator
operator = $OPERATOR_JWT

# System account
system_account = $SYSTEM_ACCOUNT

jetstream: {
  store_dir: /home/runner/data
  domain: "$JETSTREAM_DOMAIN"
  max_memory_store: $NATS_JS_MAX_MEMORY_STORE
  max_file_store: $NATS_JS_MAX_FILE_STORE
  cipher: chachapoly
  key: "$JETSTREAM_KEY"
  prev_encryption_key: "$JETSTREAM_PREV_KEY"
}

leafnodes: {
  reconnect: "10s"
  remotes: $NATS_LEAF_REMOTES
}

mqtt: {
  port: $NATS_MQTT_PORT
  tls: {
    ca_file: "$NATS_SSL_DIR/$NATS_MQTT_CERT_NAME/ca.crt"
    cert_file: "$NATS_SSL_DIR/$NATS_MQTT_CERT_NAME/tls.crt"
    key_file: "$NATS_SSL_DIR/$NATS_MQTT_CERT_NAME/tls.key"
    handshake_first: true
    timeout: "3s"
  }
}

resolver: {
  type: full
  dir: "$NATS_JWT_DIR"
  allow_delete: false
  interval: "10m"
}
