parameters:
  nodeVersion: ''
jobs:
- job: ${{ format('Node_{0}', parameters.nodeVersion) }}
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: ${{ format('{0}.x', parameters.nodeVersion) }}
    displayName: 'Install Node.js'
  - script: |
      npm i
    displayName: Install dependencies

  - script: |
      npm test
    displayName: 'unit tests'

  - script: |
      npm run postman_test
    displayName: 'api tests'

  - script: |
      echo "npm test"
    displayName: 'integration tests'