parameters:
  nodeVersion: ''
jobs:
- job: ${{ format('Node_{0}', parameters.nodeVersion) }}
  pool:
    vmImage: 'Ubuntu-18.04'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: ${{ format('{0}.x', parameters.nodeVersion) }}
    displayName: 'Install Node.js'
  - script: |
      npm i
    displayName: Install dependencies

  - script: |
      npm run test -- junit
    displayName: 'unit tests'

  - script: |
      npm run postman_test
    displayName: 'integration tests'
  # Publish Test Results
  # Publish test results to Azure Pipelines
  - script: |
      ls -l
    displayName: 'list files (looking for test results)'
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit, cTest
      testResultsFiles: '*-results.xml' 
      searchFolder: '$(System.DefaultWorkingDirectory)' # Optional
      #mergeTestResults: false # Optional
      #failTaskOnFailedTests: false # Optional
      #testRunTitle: # Optional
      buildPlatform: ${{ format('Node_{0}', parameters.nodeVersion) }} # Optional
      testRunTitle: ${{ format('Node_{0}', parameters.nodeVersion) }} # Optional
      #buildConfiguration: # Optional
      #publishRunAttachments: true # Optional