module.exports = {
  CMD: 'command',
  CMD_LIST: 'list',
  CMD_ADD: 'add',
  CMD_UPDATE: 'update',
  CMD_REMOVE: 'remove',
  CMD_INFO: 'info',
  CMD_PROVISIONING_KEY: 'provisioning-key',
  CMD_HELP: 'help',
  CMD_START: 'start',
  CMD_STOP: 'stop',
  CMD_STATUS: 'status',
  CMD_VERSION: 'version',
  CMD_USER: 'user',
  CMD_CONFIG: 'config',
  CMD_COMSAT: 'comsat',
  CMD_PROXY: 'proxy',
  CMD_IOFOG: 'iofog',
  CMD_GENERATE_TOKEN: 'generate-token',
}