module.exports = {
  development: {
    dialect: 'postgres',
    logging: console.log,
    operatorsAliases: false,
    transactionType: 'IMMEDIATE',
    pool: {
      maxactive: 5,
      max: 5,
      min: 1,
      idle: 20000,
    },
    database: 'iofog_controller_dev',
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    host: process.env.DB_HOST || 'localhost',
    port: process.env.DB_PORT || 5432,
  },
  test: {
    dialect: 'postgres',
    logging: false,
    operatorsAliases: false,
    transactionType: 'IMMEDIATE',
    pool: {
      maxactive: 5,
      max: 5,
      min: 1,
      idle: 20000,
    },
    database: 'iofog_controller_test',
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    host: process.env.DB_HOST || 'localhost',
    port: process.env.DB_PORT || 5432,
  },
  production: {
    dialect: 'postgres',
    logging: false,
    operatorsAliases: false,
    transactionType: 'IMMEDIATE',
    pool: {
      maxactive: 5,
      max: 5,
      min: 1,
      idle: 20000,
    },
    database: 'iofog_controller',
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    host: process.env.DB_HOST || 'localhost',
    port: process.env.DB_PORT || 5432,
  },
}
