export declare const abs: (x: number) => number;
export declare const atLeast: (...values: number[]) => number;
export declare const atMost: (...values: number[]) => number;
export declare const ceil: (x: number) => number;
export declare const dividedBy: (v: number, arg: number) => number;
export declare const floor: (x: number) => number;
export declare const minus: (v: number, arg: number) => number;
export declare const modulo: (v: number, arg: number) => number;
export declare const times: (v: number, arg: number) => number;
export declare function round(v: number, arg?: number): number;
export declare function plus(v: number, arg: number): number;
export declare function sortNatural(input: any[], property?: string): any[];
