export declare function append(v: string, arg: string): string;
export declare function prepend(v: string, arg: string): string;
export declare function lstrip(v: string): string;
export declare function downcase(v: string): string;
export declare function upcase(str: string): string;
export declare function remove(v: string, arg: string): string;
export declare function removeFirst(v: string, l: string): string;
export declare function rstrip(str: string): string;
export declare function split(v: string, arg: string): string[];
export declare function strip(v: string): string;
export declare function stripNewlines(v: string): string;
export declare function capitalize(str: string): string;
export declare function replace(v: string, pattern: string, replacement: string): string;
export declare function replaceFirst(v: string, arg1: string, arg2: string): string;
export declare function truncate(v: string, l?: number, o?: string): string;
export declare function truncatewords(v: string, l?: number, o?: string): string;
