import { OperatorToken } from '../tokens/operator-token';
import { DelimitedToken } from '../tokens/delimited-token';
import { IdentifierToken } from '../tokens/identifier-token';
import { TagToken } from '../tokens/tag-token';
import { HTMLToken } from '../tokens/html-token';
import { OutputToken } from '../tokens/output-token';
import { PropertyAccessToken } from '../tokens/property-access-token';
import { LiteralToken } from '../tokens/literal-token';
import { QuotedToken } from '../tokens/quoted-token';
import { NumberToken } from '../tokens/number-token';
import { RangeToken } from '../tokens/range-token';
export declare function isDelimitedToken(val: any): val is DelimitedToken;
export declare function isOperatorToken(val: any): val is OperatorToken;
export declare function isHTMLToken(val: any): val is HTMLToken;
export declare function isOutputToken(val: any): val is OutputToken;
export declare function isTagToken(val: any): val is TagToken;
export declare function isQuotedToken(val: any): val is QuotedToken;
export declare function isLiteralToken(val: any): val is LiteralToken;
export declare function isNumberToken(val: any): val is NumberToken;
export declare function isPropertyAccessToken(val: any): val is PropertyAccessToken;
export declare function isWordToken(val: any): val is IdentifierToken;
export declare function isRangeToken(val: any): val is RangeToken;
